// <auto-generated />
using Events.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Events.CompiledDataContext
{
    [DbContext(typeof(EventDbContext))]
    public partial class EventDbContextModel : RuntimeModel
    {
        static EventDbContextModel()
        {
            var model = new EventDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static EventDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
