// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Events.CompiledDataContext
{
    public partial class EventDbContextModel
    {
        partial void Initialize()
        {
            var eventDto = EventDtoEntityType.Create(this);
            var streamDto = StreamDtoEntityType.Create(this);

            EventDtoEntityType.CreateForeignKey1(eventDto, streamDto);

            EventDtoEntityType.CreateAnnotations(eventDto);
            StreamDtoEntityType.CreateAnnotations(streamDto);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "7.0.13");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
